# Generated by Django 5.1.6 on 2025-03-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='item',
            name='spec_file',
            field=models.FileField(blank=True, null=True, upload_to='specs'),
        ),
    ]
